language: python
sudo: false

python:
  - 2.7

install:
    - make bootstrap-cfy
    - git init /tmp/gromacs-portal

script:
    - GROMACS_PORTAL=/tmp/gromacs-portal make test

notifications:
  email:
    - holer@ics.muni.cz
    - ljocha@ics.muni.cz
