forge "https://forge.puppetlabs.com"

mod "puppetlabs/stdlib",     "4.12.0"
mod "puppetlabs/concat",     "2.2.0"
mod "puppetlabs/apache",     "1.10.0"
mod "puppetlabs/firewall",   "1.8.1"
mod "puppetlabs/apt",        "2.3.0"
